/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type Role = { 'supervisor' : null } |
  { 'karyakarta' : null } |
  { 'admin' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'assignedBy' : Principal,
  'assignedTo' : Role,
  'description' : string,
  'deadline' : string,
  'attachments' : Array<ExternalBlob>,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Voter {
  'dob' : [] | [string],
  'houseNumber' : [] | [bigint],
  'signature' : [] | [ExternalBlob],
  'area' : [] | [string],
  'caste' : [] | [string],
  'name' : string,
  'srNo' : bigint,
  'mobileNo' : [] | [string],
  'education' : [] | [string],
  'profession' : [] | [string],
  'fatherHusbandName' : [] | [string],
  'office' : [] | [string],
  'educationalDocuments' : [] | [Array<ExternalBlob>],
  'district' : [] | [string],
  'taluka' : [] | [string],
  'state' : [] | [string],
  'voterId' : bigint,
  'address' : [] | [string],
  'gender' : [] | [Gender],
  'politicalIdeology' : [] | [string],
  'comments' : [] | [string],
  'photo' : [] | [ExternalBlob],
  'pincode' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVoter' : ActorMethod<
    [
      string,
      bigint,
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [Gender],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [Array<ExternalBlob>],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTask' : ActorMethod<
    [string, string, string, Role, Array<ExternalBlob>],
    undefined
  >,
  'assignUserRole' : ActorMethod<[Principal, UserProfile], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoters' : ActorMethod<[], Array<Voter>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];