/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'supervisor' : IDL.Null,
  'karyakarta' : IDL.Null,
  'admin' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedBy' : IDL.Principal,
  'assignedTo' : Role,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'attachments' : IDL.Vec(ExternalBlob),
});
export const Voter = IDL.Record({
  'dob' : IDL.Opt(IDL.Text),
  'houseNumber' : IDL.Opt(IDL.Nat),
  'signature' : IDL.Opt(ExternalBlob),
  'area' : IDL.Opt(IDL.Text),
  'caste' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'srNo' : IDL.Nat,
  'mobileNo' : IDL.Opt(IDL.Text),
  'education' : IDL.Opt(IDL.Text),
  'profession' : IDL.Opt(IDL.Text),
  'fatherHusbandName' : IDL.Opt(IDL.Text),
  'office' : IDL.Opt(IDL.Text),
  'educationalDocuments' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'district' : IDL.Opt(IDL.Text),
  'taluka' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'voterId' : IDL.Nat,
  'address' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(Gender),
  'politicalIdeology' : IDL.Opt(IDL.Text),
  'comments' : IDL.Opt(IDL.Text),
  'photo' : IDL.Opt(ExternalBlob),
  'pincode' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVoter' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(Gender),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Vec(ExternalBlob)),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'assignUserRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoters' : IDL.Func([], [IDL.Vec(Voter)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'supervisor' : IDL.Null,
    'karyakarta' : IDL.Null,
    'admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedBy' : IDL.Principal,
    'assignedTo' : Role,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'attachments' : IDL.Vec(ExternalBlob),
  });
  const Voter = IDL.Record({
    'dob' : IDL.Opt(IDL.Text),
    'houseNumber' : IDL.Opt(IDL.Nat),
    'signature' : IDL.Opt(ExternalBlob),
    'area' : IDL.Opt(IDL.Text),
    'caste' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'srNo' : IDL.Nat,
    'mobileNo' : IDL.Opt(IDL.Text),
    'education' : IDL.Opt(IDL.Text),
    'profession' : IDL.Opt(IDL.Text),
    'fatherHusbandName' : IDL.Opt(IDL.Text),
    'office' : IDL.Opt(IDL.Text),
    'educationalDocuments' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'district' : IDL.Opt(IDL.Text),
    'taluka' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'voterId' : IDL.Nat,
    'address' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(Gender),
    'politicalIdeology' : IDL.Opt(IDL.Text),
    'comments' : IDL.Opt(IDL.Text),
    'photo' : IDL.Opt(ExternalBlob),
    'pincode' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVoter' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(Gender),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Vec(ExternalBlob)),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'assignUserRole' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoters' : IDL.Func([], [IDL.Vec(Voter)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };